version: "3"

services:
  portainer:
    container_name: local_portainer
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    
    #admin123456789